// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: api/proto/exchange.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExchangeMarket_PlaceOrder_FullMethodName  = "/exchange.ExchangeMarket/PlaceOrder"
	ExchangeMarket_CancelOrder_FullMethodName = "/exchange.ExchangeMarket/CancelOrder"
)

// ExchangeMarketClient is the client API for ExchangeMarket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExchangeMarket is the core service defining the trading operations.
type ExchangeMarketClient interface {
	// Place a new order
	PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*OrderResponse, error)
	// Cancel an existing order
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelResponse, error)
}

type exchangeMarketClient struct {
	cc grpc.ClientConnInterface
}

func NewExchangeMarketClient(cc grpc.ClientConnInterface) ExchangeMarketClient {
	return &exchangeMarketClient{cc}
}

func (c *exchangeMarketClient) PlaceOrder(ctx context.Context, in *PlaceOrderRequest, opts ...grpc.CallOption) (*OrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, ExchangeMarket_PlaceOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *exchangeMarketClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, ExchangeMarket_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExchangeMarketServer is the server API for ExchangeMarket service.
// All implementations must embed UnimplementedExchangeMarketServer
// for forward compatibility.
//
// ExchangeMarket is the core service defining the trading operations.
type ExchangeMarketServer interface {
	// Place a new order
	PlaceOrder(context.Context, *PlaceOrderRequest) (*OrderResponse, error)
	// Cancel an existing order
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelResponse, error)
	mustEmbedUnimplementedExchangeMarketServer()
}

// UnimplementedExchangeMarketServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExchangeMarketServer struct{}

func (UnimplementedExchangeMarketServer) PlaceOrder(context.Context, *PlaceOrderRequest) (*OrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlaceOrder not implemented")
}
func (UnimplementedExchangeMarketServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedExchangeMarketServer) mustEmbedUnimplementedExchangeMarketServer() {}
func (UnimplementedExchangeMarketServer) testEmbeddedByValue()                        {}

// UnsafeExchangeMarketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExchangeMarketServer will
// result in compilation errors.
type UnsafeExchangeMarketServer interface {
	mustEmbedUnimplementedExchangeMarketServer()
}

func RegisterExchangeMarketServer(s grpc.ServiceRegistrar, srv ExchangeMarketServer) {
	// If the following call panics, it indicates UnimplementedExchangeMarketServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExchangeMarket_ServiceDesc, srv)
}

func _ExchangeMarket_PlaceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeMarketServer).PlaceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeMarket_PlaceOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeMarketServer).PlaceOrder(ctx, req.(*PlaceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExchangeMarket_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExchangeMarketServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExchangeMarket_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExchangeMarketServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExchangeMarket_ServiceDesc is the grpc.ServiceDesc for ExchangeMarket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExchangeMarket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "exchange.ExchangeMarket",
	HandlerType: (*ExchangeMarketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceOrder",
			Handler:    _ExchangeMarket_PlaceOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _ExchangeMarket_CancelOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/exchange.proto",
}
